### ISSUE TITLE
Fix lecture display scheme

### ISSUE THREAD

**Issue by junhoyeo** [inudevs/Today-We-Learned#1]
현재처럼 번호별 백의 자리 숫자가 분야를 나타내게 하는 것보다, 000부터 분야에 무관하게 토픽별로 주제를 만들었으면 어떨까 하네요.

**Comment by junhoyeo** [comment]
<img width="260" alt="2019-03-01 10 01 29" src="https://user-images.githubusercontent.com/32605822/53639802-988d2700-3c6d-11e9-8990-3327ae6547e2.png">

**Comment by ghost** [comment]
좋아요
